// Hardcoded scent data from T4 Scents Fragrance Oil List-1.csv
// Generated for initial app population

export const hardcodedScents = [
  {
    id: 1,
    name: 'Blushing Bride',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(light apple, rose, carnation, jasmine, suede, musk, wood)',
    essentialOils: 'patchouli',
    createdBy: 'admin@example.com',
    createdAt: '2024-01-01',
    archivedAt: null
  },
  {
    id: 2,
    name: 'Bali Blue Surf',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(lemon, mandarin blossom, sea water, coconut, grapefruit blossom, waterlily, musk, sea moss, amberwood)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-01-02',
    archivedAt: null
  },
  {
    id: 3,
    name: 'Farmer\'s Market',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(citrus, basil, chamomile, orange peel, mint, agave, tomato leaf)',
    essentialOils: 'lemon and orange',
    createdBy: 'admin@example.com',
    createdAt: '2024-01-03',
    archivedAt: null
  },
  {
    id: 4,
    name: 'Cabin Retreat',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(orange peel, ginger, spice, cypress, clove, pine, fir)',
    essentialOils: 'lemon, fir needle, gurjun balsam',
    createdBy: 'admin@example.com',
    createdAt: '2024-01-04',
    archivedAt: null
  },
  {
    id: 5,
    name: 'Maple Chai + Cream',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(ginger, nutmeg, orange, maple, cinnamon, vanilla, brown sugar, buttermilk)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-01-05',
    archivedAt: null
  },
  {
    id: 6,
    name: 'Merry Maple Bourbon',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(sweet maple, spiced bourbon, cedarwood)',
    essentialOils: 'patchouli, gurjan balsam, cedarwood',
    createdBy: 'admin@example.com',
    createdAt: '2024-01-06',
    archivedAt: null
  },
  {
    id: 7,
    name: 'Coffee Latte',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(coffee bean, cream, vanilla)',
    essentialOils: 'coffee, nutmeg',
    createdBy: 'admin@example.com',
    createdAt: '2024-01-07',
    archivedAt: null
  },
  {
    id: 8,
    name: 'Oatmeal Milk + Honey',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(almond, oats, tonka bean, musk, vanilla bean, honey)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-01-08',
    archivedAt: null
  },
  {
    id: 9,
    name: 'Winter Citrus Wreath',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(citrus, pine, clove, musk, woody)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-01-09',
    archivedAt: null
  },
  {
    id: 10,
    name: 'Berry Christmas',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(raspberry, hollyberry, black raspberry, orange zest, apple, lemon, nectarine, jasmine, musk)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-01-10',
    archivedAt: null
  },
  {
    id: 11,
    name: 'Wild Mountain Honey',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(jasmine, honey, rose, orange blossom, vanilla, tonka)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-01-11',
    archivedAt: null
  },
  {
    id: 12,
    name: 'Citrus Evergreen',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(bright orange, evergreen, clove, cinnamon stick, balsam, cedar, vetiver)',
    essentialOils: 'fir needle',
    createdBy: 'admin@example.com',
    createdAt: '2024-01-12',
    archivedAt: null
  },
  {
    id: 13,
    name: 'Bourbon Strawberry + Vanilla',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(strawberry, bourbon, vanilla)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-01-13',
    archivedAt: null
  },
  {
    id: 14,
    name: 'Saltwater Orchid',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(citrus, ozone, floral, greenery, musk)',
    essentialOils: 'orange, california',
    createdBy: 'admin@example.com',
    createdAt: '2024-01-14',
    archivedAt: null
  },
  {
    id: 15,
    name: 'Magnolia + Pink Peonies',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(cherry blossom, peach, citrus, magnolia, peony, jasmine, amber, powder, cedar, musk, woods)',
    essentialOils: 'orange',
    createdBy: 'admin@example.com',
    createdAt: '2024-01-15',
    archivedAt: null
  },
  {
    id: 16,
    name: 'Sweet Bergamot + Tea Blossom',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(citrus, aromatic, floral, aquatic, woody, musk)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-01-16',
    archivedAt: null
  },
  {
    id: 17,
    name: 'Oh Snap! Gingerbread',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(almond, ginger, spice, sweet vanilla)',
    essentialOils: 'bergamot',
    createdBy: 'admin@example.com',
    createdAt: '2024-01-17',
    archivedAt: null
  },
  {
    id: 18,
    name: 'Snickerdoodle',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(cinnamon, sugar, butter, honey, vanilla, cream)',
    essentialOils: 'patchouli, bergamot',
    createdBy: 'admin@example.com',
    createdAt: '2024-01-18',
    archivedAt: null
  },
  {
    id: 19,
    name: 'Vampire\'s Kiss',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(ripe red strawberries, jasmine blooms, dark plum)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-01-19',
    archivedAt: null
  },
  {
    id: 20,
    name: 'Cheirosa \'71 (salted caramel & toasted macadamia)',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(vanilla, sea salt, toasted macadamia nut, white chocolate, caramel, tonka bean, coconut blossom)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-01-20',
    archivedAt: null
  },
  {
    id: 21,
    name: 'Autum in the Park',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(apple, brown sugar, cedarwood)',
    essentialOils: 'patchouli',
    createdBy: 'admin@example.com',
    createdAt: '2024-01-21',
    archivedAt: null
  },
  {
    id: 22,
    name: 'Peppermint Swirt',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(peppermint, mint, eucalyptus, vanilla, sandalwood)',
    essentialOils: 'cornmint, peppermint',
    createdBy: 'admin@example.com',
    createdAt: '2024-01-22',
    archivedAt: null
  },
  {
    id: 23,
    name: 'Christmas Wish',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(cookies, pine scent, vanilla, sugarcane)',
    essentialOils: 'fir needle, lemon',
    createdBy: 'admin@example.com',
    createdAt: '2024-01-23',
    archivedAt: null
  },
  {
    id: 24,
    name: 'Farmstand Apple',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(vanilla, pear, fresh farmstand apples, musk, woods)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-01-24',
    archivedAt: null
  },
  {
    id: 25,
    name: 'Spiced Pear & Earl Grey',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(sugared pears, crisp apples, lemon, earl gray tea, honey, nutmeg, cinnamon sticks, vanilla bean, simple syrup)',
    essentialOils: 'lemon, orange, petitgrain, black pepper, cedarwood, cinnamon leaf, fir balsam',
    createdBy: 'admin@example.com',
    createdAt: '2024-01-25',
    archivedAt: null
  },
  {
    id: 26,
    name: 'Autumn Wreath',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(crisp apple, peach, pine, cinnamon, clove, autumn leaves, warm vanilla, musk, soft woods)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-01-26',
    archivedAt: null
  },
  {
    id: 27,
    name: 'Spanish Sunset',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(spanish sanguinelli, lemongrass, sparkling grapefruit, green apple, black currant, sweet rhubarb, white jasmine, soft musk, vanilla)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-01-27',
    archivedAt: null
  },
  {
    id: 28,
    name: 'Mahagony Teakwood',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(citrus, ozone, jasmine, lily, woods, teakwood, musk, moss)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-01-28',
    archivedAt: null
  },
  {
    id: 29,
    name: 'Sea Salt & Wood Sage',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(sea salt, coconut water, salted ocean mist, lavender, sage, lemonwood, driftwood, moss, amber)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-01-29',
    archivedAt: null
  },
  {
    id: 30,
    name: 'Mistletoe Memories',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(orange peel, iced holly, mulled cider, mistletoe, cinnamon, cedarwood, muck)',
    essentialOils: 'cedarwood, fir needle, lemon, orange',
    createdBy: 'admin@example.com',
    createdAt: '2024-01-30',
    archivedAt: null
  },
  {
    id: 31,
    name: 'Christmas Cottage',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(poached pear, mulled spices, tart tangerine, cinnamon leaf, spicy clove, pomegranate, sparkling ginger, tonka bean, madagascan vanilla, ground nutmeg)',
    essentialOils: 'cinamon leaf, clove leaf, ginger, orange',
    createdBy: 'admin@example.com',
    createdAt: '2024-01-31',
    archivedAt: null
  },
  {
    id: 32,
    name: 'Japanese Cherry Blossom',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(white lily, asian pear, warm vanilla, violet, mimosa petals, white jasmine, sandalwood, cherry blossoms)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-02-01',
    archivedAt: null
  },
  {
    id: 33,
    name: 'Smiley Face',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(pineapple, passion fruit, yuzu, apple, orchid, musk)',
    essentialOils: 'citronella, lemon',
    createdBy: 'admin@example.com',
    createdAt: '2024-02-02',
    archivedAt: null
  },
  {
    id: 34,
    name: 'One In A Million',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(gardenia, bergamot, orange, lemon, amber, jasmine, tuberose violet flowers)',
    essentialOils: 'musk, patchouli, woods',
    createdBy: 'admin@example.com',
    createdAt: '2024-02-03',
    archivedAt: null
  },
  {
    id: 35,
    name: 'Sea Salt & Orchid',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(orange, sea salt, amber)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-02-04',
    archivedAt: null
  },
  {
    id: 36,
    name: 'Orange Blosoom',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(bergamot, orange blossom, jasmine, sandalwood)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-02-05',
    archivedAt: null
  },
  {
    id: 37,
    name: 'Amber Noir',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(plum, citrus, amber, jasmine)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-02-06',
    archivedAt: null
  },
  {
    id: 38,
    name: 'Honeysuckle Jasmine',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(lemon, ginger, honeysuckle, jasmine)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-02-07',
    archivedAt: null
  },
  {
    id: 39,
    name: 'Magnolia & Peony',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(cherry blossom, bergamot, magnolia, peony)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-02-08',
    archivedAt: null
  },
  {
    id: 40,
    name: 'Citrus Sunshine',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(mandarin, pineapple, lemon, musk)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-02-09',
    archivedAt: null
  },
  {
    id: 41,
    name: 'Black Cherry Merlot',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(apple, black currant, black cherry, merlot, red wine, vanilla, oak, amber)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-02-10',
    archivedAt: null
  },
  {
    id: 42,
    name: 'Azure Coast',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(marine, honeydew melon, apple, lily of the valley, jasmine, sandalwood)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-02-11',
    archivedAt: null
  },
  {
    id: 43,
    name: 'Beachwood',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(sea salt, orange peel, eucalyptus, sage, patchouli, teawood, moss)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-02-12',
    archivedAt: null
  },
  {
    id: 44,
    name: 'Beach Linen',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(orange blossom, cotton blossom, linen, ozone, powder, sandalwood)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-02-13',
    archivedAt: null
  },
  {
    id: 45,
    name: 'Ocean Breeze',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(lemon, lime, sea salt, green floral, cotton blossom, musk, violet, wood)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-02-14',
    archivedAt: null
  },
  {
    id: 46,
    name: 'Leather',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(saffron, incense, leather, amber)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-02-15',
    archivedAt: null
  },
  {
    id: 47,
    name: 'Leather & Labdanum',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(bergamot, rose, lavender, labdanum, leather, tobacco leaves)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-02-16',
    archivedAt: null
  },
  {
    id: 48,
    name: 'Whiskey',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(whiskey, tonka bean, oak, smoke)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-02-17',
    archivedAt: null
  },
  {
    id: 49,
    name: 'Coffee Shop',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(coffee, caramel, sugar, vanilla, milk)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-02-18',
    archivedAt: null
  },
  {
    id: 50,
    name: 'Palo Santo & Sandalwood',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(moss, bergamot, incense, saffron, palo santo, patchouli, sandalwood)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-02-19',
    archivedAt: null
  },
  {
    id: 51,
    name: 'Cactus Flower & Jade',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(aloe, agave, chrysanthemum, green leaves, patchouli)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-02-20',
    archivedAt: null
  },
  {
    id: 52,
    name: 'Fresh Linen',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(lemon, linen, green floral, light musk)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-02-21',
    archivedAt: null
  },
  {
    id: 53,
    name: 'Coastal Cottage',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(bergamot, sea salt, peony, mint, light musk, marine)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-02-22',
    archivedAt: null
  },
  {
    id: 54,
    name: 'White Sage & Lavendar',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(lavender, chamomile, sage, rosemary, sandalwood)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-02-23',
    archivedAt: null
  },
  {
    id: 55,
    name: 'White Tea',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(mandarin, lemon, bergamot, ginger, jasmine, white tea)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-02-24',
    archivedAt: null
  },
  {
    id: 56,
    name: 'White Eucalyptus',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(marine, spearmint, lemon, eucalyptus, sea salt, powder)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-02-25',
    archivedAt: null
  },
  {
    id: 57,
    name: 'Green Tea & Lemongrass',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(lemongrass, orange, lemon, jasmine, green tea, light musk)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-02-26',
    archivedAt: null
  },
  {
    id: 58,
    name: 'Cashmere Musk',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(bergamot, saffron, violet, lily of the valley, amber, powder, vetiver)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-02-27',
    archivedAt: null
  },
  {
    id: 59,
    name: 'Cashmere Plum',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(citrus, plum, black cherry, light musk, amber, vanilla)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-02-28',
    archivedAt: null
  },
  {
    id: 60,
    name: 'Macintosh Apple',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(green leaves, pear, apple, vanilla, cedar)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-02-29',
    archivedAt: null
  },
  {
    id: 61,
    name: 'Grapefruit & Mangosteen',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(orange, orange peel, mango, grapefruit, peach, cedar, red currant)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-03-01',
    archivedAt: null
  },
  {
    id: 62,
    name: 'Caribbean Teakwood',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(leather, all spice, teakwood, tobacco leaves, sandalwood, peppercorn, amber)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-03-02',
    archivedAt: null
  },
  {
    id: 63,
    name: 'Dragon\'s Blood',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(orange, orange blossom, cedar, patchouli, incense, tonka bean)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-03-03',
    archivedAt: null
  },
  {
    id: 64,
    name: 'Moonflower Nectar',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(pear, agave, rose, marine, cherry blossom, powder, musk, amber)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-03-04',
    archivedAt: null
  },
  {
    id: 65,
    name: 'Black Sea',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(petitgrain, sea salt, plum, eucalyptus, powder, sandalwood)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-03-05',
    archivedAt: null
  },
  {
    id: 66,
    name: 'Black Coral & Moss',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(marine, pineapple, lavender, bamboo, vetiver, amber, cedar)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-03-06',
    archivedAt: null
  },
  {
    id: 67,
    name: 'Vanilla Orchard',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(orange, green leaves, jasmine, sandalwood, musk, vanilla)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-03-07',
    archivedAt: null
  },
  {
    id: 68,
    name: 'Velvet Vanilla',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(linen, amaretto, jasmine, smoke, musk, parlie, vanilla, amber)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-03-08',
    archivedAt: null
  },
  {
    id: 69,
    name: 'Glacier Lily',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(ozone, eucalyptus, lavender, amber, patchouli)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-03-09',
    archivedAt: null
  },
  {
    id: 70,
    name: 'Lemon',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(lemon)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-03-10',
    archivedAt: null
  },
  {
    id: 71,
    name: 'Lemon Verbena',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(lemon, sugar, lemon peel, lemon verbena, lemongrass, light musk)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-03-11',
    archivedAt: null
  },
  {
    id: 72,
    name: 'Orchard Pear',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(apple, citrus, pear, sugar, musk, wood)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-03-12',
    archivedAt: null
  },
  {
    id: 73,
    name: 'Persimmon Citron',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(orange peel, citron, eucalyptus, peach, persimmon, tangerine, red currant, bamboo)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-03-13',
    archivedAt: null
  },
  {
    id: 74,
    name: 'Olive Leaf & Citron',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(bergamot, marine, lemon, grass, rose, olive, wood, musk)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-03-14',
    archivedAt: null
  },
  {
    id: 75,
    name: 'Strawberry Cheesecake',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(strawberry, orange peel, lemon peel, graham cracker, sugar, vanilla, cream)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-03-15',
    archivedAt: null
  },
  {
    id: 76,
    name: 'Peach Nectar',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(amaretto, lime, banana, papaya, peach, mango, pear, green leaves, tonka bean)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-03-16',
    archivedAt: null
  },
  {
    id: 77,
    name: 'Arctic Ivy',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(eucalyptus, bergamot, lemon, sage, fig, rose, amber, musk)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-03-17',
    archivedAt: null
  },
  {
    id: 78,
    name: 'Apple Harvest',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(orange peel, cinnamon, nutmeg, apple, clove, vanilla)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-03-18',
    archivedAt: null
  },
  {
    id: 79,
    name: 'Harvest Moon',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(green leaves, pear, plum, cinnamon, sugar, smoke, sandalwood)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-03-19',
    archivedAt: null
  },
  {
    id: 80,
    name: 'Fallen Leaves',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(cinnamon, citrus, chrysanthemum, berry, green leaves, apple, pecan, cedar)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-03-20',
    archivedAt: null
  },
  {
    id: 81,
    name: 'Autumn Glow',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(apple, cinnamon, clove, pine, eucalyptus, juniper, cranberry, cedar)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-03-21',
    archivedAt: null
  },
  {
    id: 82,
    name: 'Christmas Hearth',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(cinnamon, orange peel, ginger, clove, cypress, pine, fir)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-03-22',
    archivedAt: null
  },
  {
    id: 83,
    name: 'Mistletoe',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(eucalyptus, red currant, clove, pine, fir, patchouli, cedar)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-03-23',
    archivedAt: null
  },
  {
    id: 84,
    name: 'Wassail',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(orange peel, cinnamon, lemon, cranberry, apple cider, red wine, wood)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-03-24',
    archivedAt: null
  },
  {
    id: 85,
    name: 'Apothecary',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(peppercorn, coriander, sage, moss, patchouli, chamomile, balsam)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-03-25',
    archivedAt: null
  },
  {
    id: 86,
    name: 'Baltic Dew',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(ozone, apple, lemon, sage, eucalyptus, amber, patchouli)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-03-26',
    archivedAt: null
  },
  {
    id: 87,
    name: 'Cherry Eclipse',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(black cherry, almond, raspberry, vanilla, vetiver, cedar, sandalwood)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-03-27',
    archivedAt: null
  },
  {
    id: 88,
    name: 'Elderberry Nectar',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(green tea, mandarin, elderberry, raspberry, geranium, oak, sandalwood)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-03-28',
    archivedAt: null
  },
  {
    id: 89,
    name: 'Golden Moon Milk',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(bergamot, lemon, turmeric, milk, lavender, cardamom, vanilla, tonka bean, musk)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-03-29',
    archivedAt: null
  },
  {
    id: 90,
    name: 'Lychee Blush',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(apple, pear, lychee, peony, lotus flower, musk, sugar)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-03-30',
    archivedAt: null
  },
  {
    id: 91,
    name: 'Meadow Thistle',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(sage, eucalyptus, orange peel, clover, pine, thistle, moss)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-03-31',
    archivedAt: null
  },
  {
    id: 92,
    name: 'Royal Melon Fizz',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(spearmint, champagne, honeydew melon, cantaloupe, praline)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-04-01',
    archivedAt: null
  },
  {
    id: 93,
    name: 'Sea & Stone',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(peppercorn, sea salt, pear, aldehydic, labdanum, freesia, grass, patchouli, cedar)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-04-02',
    archivedAt: null
  },
  {
    id: 94,
    name: 'Solar Petals & Tangerine',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(neroli, tangerine, bergamot, orange blossom, sea salt, vanilla, cedar)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-04-03',
    archivedAt: null
  },
  {
    id: 95,
    name: 'Spun Cotton',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(sage, cotton blossom, lavender, patchouli, amber, cedar, palo santo)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-04-04',
    archivedAt: null
  },
  {
    id: 96,
    name: 'Starfruit & Kiwi',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(mango, mandarin, starfruit, guava, papaya, kiwi, amber, sandalwood)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-04-05',
    archivedAt: null
  },
  {
    id: 97,
    name: 'Vanilla Cake Pop',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(coconut, lemon, butter, sugar, vanilla)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-04-06',
    archivedAt: null
  },
  {
    id: 98,
    name: 'Volcanic Sand & Sage',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(chamomile, pear, sage, rose, lavender, palo santo, patchouli)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-04-07',
    archivedAt: null
  },
  {
    id: 99,
    name: 'Warm Croissant',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(sugar, honey, lemon, butter, walnut, almond, caramel)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-04-08',
    archivedAt: null
  },
  {
    id: 100,
    name: 'Wisteria Vines',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(violet, lemon, ozone, freesia, lilac, wisteria, musk, verbena)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-04-09',
    archivedAt: null
  },
  {
    id: 101,
    name: 'Water Lily',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(violet, marine, mimosa, lily, cardamom, cottom blossom, tonka bean, sugar)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-04-10',
    archivedAt: null
  },
  {
    id: 102,
    name: 'Enoki Forest',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(citrus, aldehydic, mushroom, earth, moss, sandalwood, cedar)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-04-11',
    archivedAt: null
  },
  {
    id: 103,
    name: 'Gilded Mandarin',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(mandarin, bergamot, cassis, coconut, jasmine, sandalwood, musk)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-04-12',
    archivedAt: null
  },
  {
    id: 104,
    name: 'Obsidian',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(bergamot, hemp, peppercorn, rum, patchouli, sandalwood, leather)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-04-13',
    archivedAt: null
  },
  {
    id: 105,
    name: 'Ambered Vanille',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(coconut, sugar, vanilla, jasmine, amber, patchouli, musk)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-04-14',
    archivedAt: null
  },
  {
    id: 106,
    name: 'Elderflower Aperitif',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(cassis, apple, raspberry, elderflower, tuberose, ylang ylang, cedar, amber)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-04-15',
    archivedAt: null
  },
  {
    id: 107,
    name: 'White Peach Blossom',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(peach, orange peel, rose, marine, sweet pea, teakwood, mango, musk)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-04-16',
    archivedAt: null
  },
  {
    id: 108,
    name: 'Speakeasy',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(peppercorn, orange, violet, pine, sage, leather, juniper)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-04-17',
    archivedAt: null
  },
  {
    id: 109,
    name: 'Peony & Lychee',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(lychee, raspberry, peach nectar, peony, violet leaf, d\'anjou pear, caramel, sandalwood)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-04-18',
    archivedAt: null
  },
  {
    id: 110,
    name: 'Volcano type',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(valencia orange, italian mandarin, white pineapple, cara orange, white strawberry, french raspberry, navel orange, honeybell orange, orange leaves)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-04-19',
    archivedAt: null
  },
  {
    id: 111,
    name: 'Palo Santo',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(citron, vanilla orchid, heliotrope, amber mist, tonka bean, palo santo, black cedar, oakmoss)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-04-20',
    archivedAt: null
  },
  {
    id: 112,
    name: 'Peony Tea Rose',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(green apple, citrus, peony, tea rose, muguet, jasmine)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-04-21',
    archivedAt: null
  },
  {
    id: 113,
    name: 'London Fog',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(bergamot, petitgrain, lemon, black tea, rosemary, chamomile, dried tea, sage leaf, lavender)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-04-22',
    archivedAt: null
  },
  {
    id: 114,
    name: 'Matcha Moon',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(neon pistachio, candied lemon, bergamot, almond, jasmine, matcha powder, amber, musk, sandalwood)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-04-23',
    archivedAt: null
  },
  {
    id: 115,
    name: 'Sweater Weather',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(autumn leaves, spearmind, eucalyptus, juniper berry, sage, wood)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-04-24',
    archivedAt: null
  },
  {
    id: 116,
    name: 'Flannel',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(bergamot, mahogany, musk)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-04-25',
    archivedAt: null
  },
  {
    id: 117,
    name: 'Home For Christmas',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(holiday fruit, clove, mint, pine, sugared berries, cinnamon, vanilla, light musk)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-04-26',
    archivedAt: null
  },
  {
    id: 118,
    name: 'Salted Caramel',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(butter, cinnamon, coconut, vanilla, maple)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-04-27',
    archivedAt: null
  },
  {
    id: 119,
    name: 'Love Spell',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(crisp citrus, berry, green, lavender, musk)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-04-28',
    archivedAt: null
  },
  {
    id: 120,
    name: 'Black Ice',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(orange, pine, citrus, violet, lavender, jasmine, sandalwood, musk)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-04-29',
    archivedAt: null
  },
  {
    id: 121,
    name: 'Volcano',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(fruit, water, tropical, foliage, exotic, driftwood)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-04-30',
    archivedAt: null
  },
  {
    id: 122,
    name: 'Harvest Gathering (type)',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(fruit, berries, cinnamon, clove, spice)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-05-01',
    archivedAt: null
  },
  {
    id: 123,
    name: 'Endless Weekend',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(citrus, berry, magnolia, lily, vanilla, sandalwood, musk)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-05-02',
    archivedAt: null
  },
  {
    id: 124,
    name: 'Cucumber & Green Tea',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(orange, lime, green leaves, cucumber, clove, rose, jasmine, musk)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-05-03',
    archivedAt: null
  },
  {
    id: 125,
    name: 'Mahogany Teakwood',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(fresh lavender, geranium, warm mahogany, earthy wood)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-05-04',
    archivedAt: null
  },
  {
    id: 126,
    name: 'Sea Salt Oasis',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(seafoam, green melon, lotus flower, lily pads, water iris, blue kelp, driftwood)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-05-05',
    archivedAt: null
  },
  {
    id: 127,
    name: 'Sugar Cookie Royale',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(sugar, bakery, dough, butter, vanilla)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-05-06',
    archivedAt: null
  },
  {
    id: 128,
    name: 'Wild Daisy Dream',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(wild strawberry, tea rose, wild daisies, marigold daffodil, pink poppies, blonde woods, sweet sugar, sheer musk)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-05-07',
    archivedAt: null
  },
  {
    id: 129,
    name: 'Georgia Peach',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(citrus, peach, green, fruit, vanilla, musk)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-05-08',
    archivedAt: null
  },
  {
    id: 130,
    name: 'Vanilla Buttercream Crunch',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(butter, coconut, vanilla, maple)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-05-09',
    archivedAt: null
  },
  {
    id: 131,
    name: 'Cherry Heat',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(sour cherry, saffron, leather, osmanthus, apricot, smoked guaiacwood)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-05-10',
    archivedAt: null
  },
  {
    id: 132,
    name: 'Narcissist',
    topNotes: '',
    middleNotes: '',
    baseNotes: '',
    allNotes: '(peach, raspberry, osmanthus, cinnamon, anise, rose, orange blossom, patchouli, sandalwood, egyptian musk)',
    essentialOils: '',
    createdBy: 'admin@example.com',
    createdAt: '2024-05-11',
    archivedAt: null
  }
]
